### ISSUE TITLE
Image upload failed on hidora server

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-chaux-de-fonds/Interlab#108]
```
Internal Server Error: /admin/filer/clipboard/operations/upload/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response 
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/filer/admin/clipboardadmin.py", line 112, in ajax_upload  
    file_obj.save()
  File "/usr/local/lib/python3.10/site-packages/filer/models/imagemodels.py", line 48, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/filer/models/abstract.py", line 76, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/filer/models/filemodels.py", line 224, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/polymorphic/models.py", line 91, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 789, in save_base
    parent_inserted = self._save_parents(cls, using, update_fields)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 818, in _save_parents
    updated = self._save_table(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1339, in as_sql
    value_rows = [
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1340, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1340, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1291, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/fields/files.py", line 308, in pre_save
    file.save(file.name, file.file, save=False)
  File "/usr/local/lib/python3.10/site-packages/filer/fields/multistorage_file.py", line 120, in save
    super().save(name, content, save)
  File "/usr/local/lib/python3.10/site-packages/easy_thumbnails/files.py", line 643, in save
    super().save(name, content, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/fields/files.py", line 88, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/usr/local/lib/python3.10/site-packages/django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "/usr/local/lib/python3.10/site-packages/django/core/files/storage.py", line 255, in _save
    os.makedirs(directory, exist_ok=True)
  File "/usr/local/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/code/media'
```

**Comment by ioknox** [comment]
Fixed by adding media folder to docker-compose.yml file and route /media/ to nginx
