### ISSUE TITLE
FIX: ajout d'une formation a un utilisateur

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-chaux-de-fonds/Interlab#152]
```Environment:


Request Method: POST
Request URL: http://hidora.fablab-chaux-de-fonds.ch/accounts/superuser-profile-edit/1

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/code/accounts/views.py", line 282, in form_valid
    form.update_training_validation(self)
  File "/code/accounts/forms.py", line 173, in update_training_validation
    if not training.pk in self.initial['training']:

Exception Type: KeyError at /accounts/superuser-profile-edit/1
Exception Value: 'training'`
```

Correction: lors de la validation, check si key training existe ?

**Comment by raphaelmonnard** [comment]
Fix: 78f121f7c2979f837e44e7c5d57bfd6f0183c236
